### ISSUE TITLE
[BUG] Refresh causes 404

### ISSUE THREAD

**Issue by ArcaneDisgea** [XIVRotationHero/xiv-rotation-hero-angular#1]
**Describe the bug**
Refreshing the page sends you to https://app.xivrotationhero.com/browser which is 404'd in NGINX

**To Reproduce**
1. Open https://app.xivrotationhero.com
2. Refresh

**Expected behavior**
Should redirect to https://app.xivrotationhero.com/ or display the appropriate page.

**Screenshots**
![image](https://user-images.githubusercontent.com/39720490/129618840-794709ab-8fdd-4d40-bf01-4a345d30896a.png)

**Desktop (please complete the following information):**
 - OS: Win10 20H2
 - Browser: Chrome 92.0.4515.131 (Official Build) (64-bit) (cohort: Stable)

**Additional context**
Probably just need to edit nginx config to fix this.

**Comment by SargoDarya** [comment]
The problem in the nginx configuration was a missing slash. Adding this and reloading the server was the solution.
