### ISSUE TITLE
[BUG] Cannot exit sign-in modal without refreshing.

### ISSUE THREAD

**Issue by ArcaneDisgea** [XIVRotationHero/xiv-rotation-hero-angular#2]
**Describe the bug**
Cannot exit the sign in modal after opening it.

**To Reproduce**
1. Click Sign In button
2. Try to escape its icy grip without refreshing

**Expected behavior**
Clicking outside of the modal should hide it or add an X to the corner of it so that it can be clicked away

**Screenshots**
![ljWhtw1wc3](https://user-images.githubusercontent.com/39720490/129619462-1677db10-21c2-4a74-8a72-05ed34be1259.gif)

**Desktop (please complete the following information):**
 - OS: Win10 20H2
 - Browser: Chrome 92.0.4515.131 (Official Build) (64-bit) (cohort: Stable)

**Comment by SargoDarya** [comment]
- [x] Add cross icon for closing overlay
- [x] Add click handler for closing dialog

FYI, for now you can actually close it with escape.

**Comment by SargoDarya** [comment]
Will be deployed with the next patch release.
