### ISSUE TITLE
[FEAT] Discord/Google/Other SSO

### ISSUE THREAD

**Issue by ArcaneDisgea** [XIVRotationHero/xiv-rotation-hero-angular#3]
**Is your feature request related to a problem? Please describe.**
In my best attempt to not sound like an infomercial, remembering passwords is difficult for end users and SSO is convenient as hell.

**Describe the solution you'd like**
Implement ideally Discord SSO at the minimum as an alternative to standard email/pass. Discord is fairly popular within the community and lots of tools use it for their SSO already such as:
 - [xivapi](https://xivapi.com)
 - [ffxivcollect](https://ffxivcollect.com)
 - [ffxivtriad](https://triad.raelys.com/)

**Comment by SargoDarya** [comment]
Will add Discord oauth for the next release and see if there's need for other Auth providers.

**Comment by SargoDarya** [comment]
This would be the suggested implementation on the frontend side. However I'm unsure how I'm going to deal with usernames in this case.

![image](https://user-images.githubusercontent.com/404206/129767103-d78eb602-280b-4d4d-9368-44d2196a3226.png)

**Comment by SargoDarya** [comment]
Scheduled to land in v0.2.0.

Backend part has already been deployed.
